# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-20.04

variables:
  imageName: 'web-visit-count-local'

steps:
- task: Docker@2
  displayName: Build container image - $(imageName)
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile

- task: Bash@3
  displayName: Download twistcli
  inputs:
    targetType: inline
    script: curl -k -u $(PCUSER):$(PCPASS) $(PC_CONSOLE)/api/v1/util/twistcli -v -o twistcli;chmod +x twistcli

- task: Bash@3
  displayName: Scan image - $(imageName):$(Build.BuildId)
  inputs:
    targetType: inline
    script: |
      ./twistcli images scan $(imageName):$(Build.BuildId) --address $(PC_CONSOLE) -u $(PCUSER) -p $(PCPASS) --details
