apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pv-claim-nfs
  namespace: web-visit-count
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: web-pv-volume-nfs
  resources:
    requests:
      storage: 1T
