apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv-volume-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/pv-data
    server: 10.4.0.5
